# see: http://docs.travis-ci.com/user/languages/perl/
# see: http://blogs.perl.org/users/neilb/2014/08/try-travis-ci-with-your-cpan-distributions.html
language: perl
perl:
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
install:
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm -n -q --skip-satisfied --notest --installdeps .
#script: prove -lr t
script:
  - PERL5OPT=-MDevel::Cover="-coverage,statement,branch,condition,path,subroutine+ignore=prove" prove -lrsv t
  - cover
after_success:
  - cover -report coveralls